### ISSUE TITLE
Adding your package to bionim

### ISSUE THREAD

**Issue by Unaimend** [kerrycobb/PhylogeNi#1]
Hi,
I am working on a package called bionim, which aims to be the standard package for bioinformatics related stuff in nim. And I wanted to ask if your package will still be maintained, if yes I would just require your package in bionim, and write a few lines in the github repo, that part of bionim is your package

Regards
Thomas Dost/Unaimend

**Comment by kerrycobb** [comment]
Hi Thomas,

I do plan to continue maintaining and developing my package. It would be great to have it included as part of your package and hopefully get some exposure to attract contributors! 

Do you have plans for DNA sequence data? I have been playing around with an Ape (R package) like implementation using 8bit integers as well as a bitset representation of nucleotides (far from successfully acheived). I’d be happy to share the code if you or someone you know of wants to run with it and use it.

-Kerry

**Comment by Unaimend** [comment]
So, I of course want include some kind of special structure for nucleotide representation but  at the moment I don't have any concrete plans, so I would be quite happy to see your approach, I the end I plan on writing a few smalish projects to show of the bionim package as a whole, so a specialized nucleotide representation is definitely on the todo list. Ill try to include your package in the next few days and give some kind of credits in the readme. If you already have a idea how those credits should look you can of course just tell me. 
Thank you for your permission

Regards
Thomas Dost

**Comment by kerrycobb** [comment]
Thanks for adding Phylogeni!

I created two repos to share some progress I’ve made on a couple of things. 

The first https://github.com/kerrycobb/nim-dna-seq <https://github.com/kerrycobb/nim-dna-seq> has the 8 bit unsigned integer representation of nucleotides that I mentioned. It’s also got Fasta and Phylip parsers. I think most of it is working. Some sections have been commented out for reasons I don’t remember. I don’t think it would take much to make them work. I would be interested in working on this more and helping incorporate it into BioNim if you are interested. I’ve kind of been waiting to find people to collaborate with on this before devoting a lot of time to it. 

This might also be useful someday https://github.com/kerrycobb/nim-nexus-lib <https://github.com/kerrycobb/nim-nexus-lib>. I’ve played around with some ideas for a Nexus file parsing library. There is still a lot of work that needs to be done but I was feeling pretty good about the general direction I was going in with it.

I won’t have a lot of free time over the next two months but should in the Summer if you want to some help with BioNim. I’ve been kind of excited to eventually work on something like this if an initiative ever got off the ground. So keep me in mind if you have ideas you want to work on.

Cheers,

Kerry

**Comment by Unaimend** [comment]
The first one looks really cool, as to the problem with deciding if it's RNA or DNA, could one use the right most bit for this, if I saw it correctly it is not used in the specification, but should probably think about the consequences a bit more. 

And I would be happy to work with you on more bioinformatic related stuff, so I hope you have two productive two months, will definitely keep you in mind.

Regards
Thomas Dost
